package completion

type FunctionMapping struct {
	Name        string
	Description string
}

var sqlKeywordMappings = []string{
	"SELECT",
	"FROM",
	"WHERE",
	"GROUP BY",
	"ORDER BY",
	"LIMIT",
	"OFFSET",
	"JOIN",
	"LEFT JOIN",
	"RIGHT JOIN",
	"INNER JOIN",
	"FULL OUTER JOIN",
	"ON",
	"AS",
	"WITH",
	"HAVING",
	"UNION ALL",
	"UNION DISTINCT",
	"DISTINCT",
	"AND",
	"OR",
	"NOT",
	"IN",
	"IS NULL",
	"IS NOT NULL",
	"LIKE",
	"BETWEEN",
	"CASE",
	"WHEN",
	"THEN",
	"ELSE",
	"END",
	"OVER",
	"PARTITION BY",
	"QUALIFY",
	"CREATE TABLE",
	"CREATE OR REPLACE VIEW",
	"INSERT INTO",
}

var sqlFunctionMappings = []FunctionMapping{
	{Name: "ABS", Description: "Computes the absolute value of X."},
	{Name: "ACOS", Description: "Computes the inverse cosine of X."},
	{Name: "ACOSH", Description: "Computes the inverse hyperbolic cosine of X."},
	{Name: "AEAD.DECRYPT_BYTES", Description: "Uses the matching key from a keyset to decrypt a BYTES ciphertext."},
	{Name: "AEAD.DECRYPT_STRING", Description: "Uses the matching key from a keyset to decrypt a BYTES ciphertext into a STRING plaintext."},
	{Name: "AEAD.ENCRYPT", Description: "Encrypts STRING plaintext, using the primary cryptographic key in a keyset."},
	{Name: "AGG", Description: "Aggregates a measure type."},
	{Name: "ANY_VALUE", Description: "Gets an expression for some row."},
	{Name: "APPENDS", Description: "Returns all rows appended to a table for a given time range."},
	{Name: "APPROX_COUNT_DISTINCT", Description: "Gets the approximate result for COUNT(DISTINCT expression)."},
	{Name: "APPROX_QUANTILES", Description: "Gets the approximate quantile boundaries."},
	{Name: "APPROX_TOP_COUNT", Description: "Gets the approximate top elements and their approximate count."},
	{Name: "APPROX_TOP_SUM", Description: "Gets the approximate top elements and sum, based on the approximate sum of an assigned weight."},
	{Name: "ARRAY", Description: "Produces an array with one element for each row in a subquery."},
	{Name: "ARRAY_AGG", Description: "Gets an array of values."},
	{Name: "ARRAY_CONCAT", Description: "Concatenates one or more arrays with the same element type into a single array."},
	{Name: "ARRAY_CONCAT_AGG", Description: "Concatenates arrays and returns a single array as a result."},
	{Name: "ARRAY_FIRST", Description: "Gets the first element in an array."},
	{Name: "ARRAY_LAST", Description: "Gets the last element in an array."},
	{Name: "ARRAY_LENGTH", Description: "Gets the number of elements in an array."},
	{Name: "ARRAY_REVERSE", Description: "Reverses the order of elements in an array."},
	{Name: "ARRAY_SLICE", Description: "Produces an array containing zero or more consecutive elements from an input array."},
	{Name: "ARRAY_TO_STRING", Description: "Produces a concatenation of the elements in an array as a STRING value."},
	{Name: "ASCII", Description: "Gets the ASCII code for the first character or byte in a STRING or BYTES value."},
	{Name: "ASIN", Description: "Computes the inverse sine of X."},
	{Name: "ASINH", Description: "Computes the inverse hyperbolic sine of X."},
	{Name: "ATAN", Description: "Computes the inverse tangent of X."},
	{Name: "ATAN2", Description: "Computes the inverse tangent of X/Y, using the signs of X and Y to determine the quadrant."},
	{Name: "ATANH", Description: "Computes the inverse hyperbolic tangent of X."},
	{Name: "AVG", Description: "Gets the average of non-NULL values. / DIFFERENTIAL_PRIVACY-supported AVG. Gets the differentially-private average of non-NULL, non-NaN values in a query with a DIFFERENTIAL_PRIVACY clause."},
	{Name: "BAG_OF_WORDS", Description: "Gets the frequency of each term (token) in a tokenized document."},
	{Name: "BIT_AND", Description: "Performs a bitwise AND operation on an expression."},
	{Name: "BIT_COUNT", Description: "Gets the number of bits that are set in an input expression."},
	{Name: "BIT_OR", Description: "Performs a bitwise OR operation on an expression."},
	{Name: "BIT_XOR", Description: "Performs a bitwise XOR operation on an expression."},
	{Name: "BOOL", Description: "Converts a JSON boolean to a SQL BOOL value."},
	{Name: "BYTE_LENGTH", Description: "Gets the number of BYTES in a STRING or BYTES value."},
	{Name: "CAST", Description: "Convert the results of an expression to the given type."},
	{Name: "CBRT", Description: "Computes the cube root of X."},
	{Name: "CEIL", Description: "Gets the smallest integral value that isn't less than X."},
	{Name: "CEILING", Description: "Synonym of CEIL."},
	{Name: "CHANGES", Description: "Returns all rows that have changed in a table for a given time range."},
	{Name: "CHAR_LENGTH", Description: "Gets the number of characters in a STRING value."},
	{Name: "CHARACTER_LENGTH", Description: "Synonym for CHAR_LENGTH."},
	{Name: "CHR", Description: "Converts a Unicode code point to a character."},
	{Name: "CODE_POINTS_TO_BYTES", Description: "Converts an array of extended ASCII code points to a BYTES value."},
	{Name: "CODE_POINTS_TO_STRING", Description: "Converts an array of extended ASCII code points to a STRING value."},
	{Name: "COLLATE", Description: "Combines a STRING value and a collation specification into a collation specification-supported STRING value."},
	{Name: "CONCAT", Description: "Concatenates one or more STRING or BYTES values into a single result."},
	{Name: "CONTAINS_SUBSTR", Description: "Performs a normalized, case-insensitive search to see if a value exists as a substring in an expression."},
	{Name: "CORR", Description: "Computes the Pearson coefficient of correlation of a set of number pairs."},
	{Name: "COS", Description: "Computes the cosine of X."},
	{Name: "COSH", Description: "Computes the hyperbolic cosine of X."},
	{Name: "COSINE_DISTANCE", Description: "Computes the cosine distance between two vectors."},
	{Name: "COT", Description: "Computes the cotangent of X."},
	{Name: "COTH", Description: "Computes the hyperbolic cotangent of X."},
	{Name: "COUNT", Description: "Gets the number of rows in the input, or the number of rows with an expression evaluated to any value other than NULL. / DIFFERENTIAL_PRIVACY-supported COUNT. Signature 1: Gets the differentially-private count of rows in a query with a DIFFERENTIAL_PRIVACY clause. Signature 2: Gets the differentially-private count of rows with a non-NULL expression in a query with a DIFFERENTIAL_PRIVACY clause."},
	{Name: "COUNTIF", Description: "Gets the number of TRUE values for an expression."},
	{Name: "COVAR_POP", Description: "Computes the population covariance of a set of number pairs."},
	{Name: "COVAR_SAMP", Description: "Computes the sample covariance of a set of number pairs."},
	{Name: "CSC", Description: "Computes the cosecant of X."},
	{Name: "CSCH", Description: "Computes the hyperbolic cosecant of X."},
	{Name: "CUME_DIST", Description: "Gets the cumulative distribution (relative position (0,1]) of each row within a window."},
	{Name: "CURRENT_DATE", Description: "Returns the current date as a DATE value."},
	{Name: "CURRENT_DATETIME", Description: "Returns the current date and time as a DATETIME value."},
	{Name: "CURRENT_TIME", Description: "Returns the current time as a TIME value."},
	{Name: "CURRENT_TIMESTAMP", Description: "Returns the current date and time as a TIMESTAMP object."},
	{Name: "DATE", Description: "Constructs a DATE value."},
	{Name: "DATE_ADD", Description: "Adds a specified time interval to a DATE value."},
	{Name: "DATE_BUCKET", Description: "Gets the lower bound of the date bucket that contains a date."},
	{Name: "DATE_DIFF", Description: "Gets the number of unit boundaries between two DATE values at a particular time granularity."},
	{Name: "DATE_FROM_UNIX_DATE", Description: "Interprets an INT64 expression as the number of days since 1970-01-01."},
	{Name: "DATE_SUB", Description: "Subtracts a specified time interval from a DATE value."},
	{Name: "DATE_TRUNC", Description: "Truncates a DATE, DATETIME, or TIMESTAMP value at a particular granularity."},
	{Name: "DATETIME", Description: "Constructs a DATETIME value."},
	{Name: "DATETIME_ADD", Description: "Adds a specified time interval to a DATETIME value."},
	{Name: "DATETIME_BUCKET", Description: "Gets the lower bound of the datetime bucket that contains a datetime."},
	{Name: "DATETIME_DIFF", Description: "Gets the number of unit boundaries between two DATETIME values at a particular time granularity."},
	{Name: "DATETIME_SUB", Description: "Subtracts a specified time interval from a DATETIME value."},
	{Name: "DATETIME_TRUNC", Description: "Truncates a DATETIME or TIMESTAMP value at a particular granularity."},
	{Name: "DENSE_RANK", Description: "Gets the dense rank (1-based, no gaps) of each row within a window."},
	{Name: "DESTINATION_NODE_ID", Description: "Gets a unique identifier of a graph edge's destination node."},
	{Name: "DETERMINISTIC_DECRYPT_BYTES", Description: "Uses the matching key from a keyset to decrypt a BYTES ciphertext, using deterministic AEAD."},
	{Name: "DETERMINISTIC_DECRYPT_STRING", Description: "Uses the matching key from a keyset to decrypt a BYTES ciphertext into a STRING plaintext, using deterministic AEAD."},
	{Name: "DETERMINISTIC_ENCRYPT", Description: "Encrypts STRING plaintext, using the primary cryptographic key in a keyset, using deterministic AEAD encryption."},
	{Name: "DIV", Description: "Divides integer X by integer Y."},
	{Name: "DLP_DETERMINISTIC_ENCRYPT", Description: "Encrypts data with a DLP compatible algorithm."},
	{Name: "DLP_DETERMINISTIC_DECRYPT", Description: "Decrypts DLP-encrypted data."},
	{Name: "DLP_KEY_CHAIN", Description: "Gets a data encryption key that's wrapped by Cloud Key Management Service."},
	{Name: "FLOAT64", Description: "Converts a JSON number to a SQL FLOAT64 value."},
	{Name: "EDGES", Description: "Gets the edges in a graph path. The resulting array retains the original order in the graph path."},
	{Name: "EDIT_DISTANCE", Description: "Computes the Levenshtein distance between two STRING or BYTES values."},
	{Name: "ELEMENT_ID", Description: "Gets a graph element's unique identifier."},
	{Name: "ENDS_WITH", Description: "Checks if a STRING or BYTES value is the suffix of another value."},
	{Name: "ERROR", Description: "Produces an error with a custom error message."},
	{Name: "EXP", Description: "Computes e to the power of X."},
	{Name: "EXTERNAL_OBJECT_TRANSFORM", Description: "Produces an object table with the original columns plus one or more additional columns."},
	{Name: "EXTERNAL_QUERY", Description: "Executes a query on an external database and returns the results as a temporary table."},
	{Name: "EXTRACT", Description: "Extracts part of a date from a DATE value. / Extracts part of a date and time from a DATETIME value. / Extracts part of an INTERVAL value. / Extracts part of a TIME value. / Extracts part of a TIMESTAMP value."},
	{Name: "EUCLIDEAN_DISTANCE", Description: "Computes the Euclidean distance between two vectors."},
	{Name: "FARM_FINGERPRINT", Description: "Computes the fingerprint of a STRING or BYTES value, using the FarmHash Fingerprint64 algorithm."},
	{Name: "FIRST_VALUE", Description: "Gets a value for the first row in the current window frame."},
	{Name: "FLOOR", Description: "Gets the largest integral value that isn't greater than X."},
	{Name: "FORMAT_DATE", Description: "Formats a DATE value according to a specified format string."},
	{Name: "FORMAT_DATETIME", Description: "Formats a DATETIME value according to a specified format string."},
	{Name: "FORMAT_TIME", Description: "Formats a TIME value according to the specified format string."},
	{Name: "FORMAT_TIMESTAMP", Description: "Formats a TIMESTAMP value according to the specified format string."},
	{Name: "FORMAT", Description: "Formats data and produces the results as a STRING value."},
	{Name: "FROM_BASE32", Description: "Converts a base32-encoded STRING value into a BYTES value."},
	{Name: "FROM_BASE64", Description: "Converts a base64-encoded STRING value into a BYTES value."},
	{Name: "FROM_HEX", Description: "Converts a hexadecimal-encoded STRING value into a BYTES value."},
	{Name: "GAP_FILL", Description: "Finds and fills gaps in a time series."},
	{Name: "GENERATE_ARRAY", Description: "Generates an array of values in a range."},
	{Name: "GENERATE_DATE_ARRAY", Description: "Generates an array of dates in a range."},
	{Name: "GENERATE_RANGE_ARRAY", Description: "Splits a range into an array of subranges."},
	{Name: "GENERATE_TIMESTAMP_ARRAY", Description: "Generates an array of timestamps in a range."},
	{Name: "GENERATE_UUID", Description: "Produces a random universally unique identifier (UUID) as a STRING value."},
	{Name: "GREATEST", Description: "Gets the greatest value among X1,...,XN."},
	{Name: "GROUPING", Description: "Checks if a groupable value in the GROUP BY clause is aggregated."},
	{Name: "HLL_COUNT.EXTRACT", Description: "Extracts a cardinality estimate of an HLL++ sketch."},
	{Name: "HLL_COUNT.INIT", Description: "Aggregates values of the same underlying type into a new HLL++ sketch."},
	{Name: "HLL_COUNT.MERGE", Description: "Merges HLL++ sketches of the same underlying type into a new sketch, and then gets the cardinality of the new sketch."},
	{Name: "HLL_COUNT.MERGE_PARTIAL", Description: "Merges HLL++ sketches of the same underlying type into a new sketch."},
	{Name: "IEEE_DIVIDE", Description: "Divides X by Y, but doesn't generate errors for division by zero or overflow."},
	{Name: "INITCAP", Description: "Formats a STRING as proper case, which means that the first character in each word is uppercase and all other characters are lowercase."},
	{Name: "INSTR", Description: "Finds the position of a subvalue inside another value, optionally starting the search at a given offset or occurrence."},
	{Name: "INT64", Description: "Converts a JSON number to a SQL INT64 value."},
	{Name: "IS_ACYCLIC", Description: "Checks if a graph path has a repeating node."},
	{Name: "IS_INF", Description: "Checks if X is positive or negative infinity."},
	{Name: "IS_NAN", Description: "Checks if X is a NaN value."},
	{Name: "IS_SIMPLE", Description: "Checks if a graph path is simple."},
	{Name: "IS_TRAIL", Description: "Checks if a graph path has a repeating edge."},
	{Name: "JSON_ARRAY", Description: "Creates a JSON array."},
	{Name: "JSON_ARRAY_APPEND", Description: "Appends JSON data to the end of a JSON array."},
	{Name: "JSON_ARRAY_INSERT", Description: "Inserts JSON data into a JSON array."},
	{Name: "JSON_EXTRACT", Description: "(Deprecated) Extracts a JSON value and converts it to a SQL JSON-formatted STRING or JSON value."},
	{Name: "JSON_EXTRACT_ARRAY", Description: "(Deprecated) Extracts a JSON array and converts it to a SQL ARRAY<JSON-formatted STRING> or ARRAY<JSON> value."},
	{Name: "JSON_EXTRACT_SCALAR", Description: "(Deprecated) Extracts a JSON scalar value and converts it to a SQL STRING value."},
	{Name: "JSON_EXTRACT_STRING_ARRAY", Description: "(Deprecated) Extracts a JSON array of scalar values and converts it to a SQL ARRAY<STRING> value."},
	{Name: "JSON_FLATTEN", Description: "Produces a new SQL ARRAY<JSON> value containing all non-array values that are either directly in the input JSON value or children of one or more consecutively nested arrays in the input JSON value."},
	{Name: "JSON_KEYS", Description: "Extracts unique JSON keys from a JSON expression."},
	{Name: "JSON_OBJECT", Description: "Creates a JSON object."},
	{Name: "JSON_QUERY", Description: "Extracts a JSON value and converts it to a SQL JSON-formatted STRING or JSON value."},
	{Name: "JSON_QUERY_ARRAY", Description: "Extracts a JSON array and converts it to a SQL ARRAY<JSON-formatted STRING> or ARRAY<JSON> value."},
	{Name: "JSON_REMOVE", Description: "Produces JSON with the specified JSON data removed."},
	{Name: "JSON_SET", Description: "Inserts or replaces JSON data."},
	{Name: "JSON_STRIP_NULLS", Description: "Removes JSON nulls from JSON objects and JSON arrays."},
	{Name: "JSON_TYPE", Description: "Gets the JSON type of the outermost JSON value and converts the name of this type to a SQL STRING value."},
	{Name: "JSON_VALUE", Description: "Extracts a JSON scalar value and converts it to a SQL STRING value."},
	{Name: "JSON_VALUE_ARRAY", Description: "Extracts a JSON array of scalar values and converts it to a SQL ARRAY<STRING> value."},
	{Name: "JUSTIFY_DAYS", Description: "Normalizes the day part of an INTERVAL value."},
	{Name: "JUSTIFY_HOURS", Description: "Normalizes the time part of an INTERVAL value."},
	{Name: "JUSTIFY_INTERVAL", Description: "Normalizes the day and time parts of an INTERVAL value."},
	{Name: "KEYS.ADD_KEY_FROM_RAW_BYTES", Description: "Adds a key to a keyset, and return the new keyset as a serialized BYTES value."},
	{Name: "KEYS.KEYSET_CHAIN", Description: "Produces a Tink keyset that's encrypted with a Cloud KMS key."},
	{Name: "KEYS.KEYSET_FROM_JSON", Description: "Converts a STRING JSON keyset to a serialized BYTES value."},
	{Name: "KEYS.KEYSET_LENGTH", Description: "Gets the number of keys in the provided keyset."},
	{Name: "KEYS.KEYSET_TO_JSON", Description: "Gets a JSON STRING representation of a keyset."},
	{Name: "KEYS.NEW_KEYSET", Description: "Gets a serialized keyset containing a new key based on the key type."},
	{Name: "KEYS.NEW_WRAPPED_KEYSET", Description: "Creates a new keyset and encrypts it with a Cloud KMS key."},
	{Name: "KEYS.REWRAP_KEYSET", Description: "Re-encrypts a wrapped keyset with a new Cloud KMS key."},
	{Name: "KEYS.ROTATE_KEYSET", Description: "Adds a new primary cryptographic key to a keyset, based on the key type."},
	{Name: "KEYS.ROTATE_WRAPPED_KEYSET", Description: "Rewraps a keyset and rotates it."},
	{Name: "KLL_QUANTILES.EXTRACT_INT64", Description: "Gets a selected number of quantiles from an INT64-initialized KLL sketch."},
	{Name: "KLL_QUANTILES.EXTRACT_FLOAT64", Description: "Gets a selected number of quantiles from a FLOAT64-initialized KLL sketch."},
	{Name: "KLL_QUANTILES.EXTRACT_POINT_INT64", Description: "Gets a specific quantile from an INT64-initialized KLL sketch."},
	{Name: "KLL_QUANTILES.EXTRACT_POINT_FLOAT64", Description: "Gets a specific quantile from a FLOAT64-initialized KLL sketch."},
	{Name: "KLL_QUANTILES.INIT_INT64", Description: "Aggregates values into an INT64-initialized KLL sketch."},
	{Name: "KLL_QUANTILES.INIT_FLOAT64", Description: "Aggregates values into a FLOAT64-initialized KLL sketch."},
	{Name: "KLL_QUANTILES.MERGE_INT64", Description: "Merges INT64-initialized KLL sketches into a new sketch, and then gets the quantiles from the new sketch."},
	{Name: "KLL_QUANTILES.MERGE_FLOAT64", Description: "Merges FLOAT64-initialized KLL sketches into a new sketch, and then gets the quantiles from the new sketch."},
	{Name: "KLL_QUANTILES.MERGE_PARTIAL", Description: "Merges KLL sketches of the same underlying type into a new sketch."},
	{Name: "KLL_QUANTILES.MERGE_POINT_INT64", Description: "Merges INT64-initialized KLL sketches into a new sketch, and then gets a specific quantile from the new sketch."},
	{Name: "KLL_QUANTILES.MERGE_POINT_FLOAT64", Description: "Merges FLOAT64-initialized KLL sketches into a new sketch, and then gets a specific quantile from the new sketch."},
	{Name: "LABELS", Description: "Gets the labels associated with a graph element."},
	{Name: "LAG", Description: "Gets a value for a preceding row."},
	{Name: "LAST_DAY", Description: "Gets the last day in a specified time period that contains a DATE value. / Gets the last day in a specified time period that contains a DATETIME value."},
	{Name: "LAST_VALUE", Description: "Gets a value for the last row in the current window frame."},
	{Name: "LAX_BOOL", Description: "Attempts to convert a JSON value to a SQL BOOL value."},
	{Name: "LAX_FLOAT64", Description: "Attempts to convert a JSON value to a SQL FLOAT64 value."},
	{Name: "LAX_INT64", Description: "Attempts to convert a JSON value to a SQL INT64 value."},
	{Name: "LAX_STRING", Description: "Attempts to convert a JSON value to a SQL STRING value."},
	{Name: "LEAD", Description: "Gets a value for a subsequent row."},
	{Name: "LEAST", Description: "Gets the least value among X1,...,XN."},
	{Name: "LEFT", Description: "Gets the specified leftmost portion from a STRING or BYTES value."},
	{Name: "LENGTH", Description: "Gets the length of a STRING or BYTES value."},
	{Name: "LN", Description: "Computes the natural logarithm of X."},
	{Name: "LOG", Description: "Computes the natural logarithm of X or the logarithm of X to base Y."},
	{Name: "LOG10", Description: "Computes the natural logarithm of X to base 10."},
	{Name: "LOGICAL_AND", Description: "Gets the logical AND of all non-NULL expressions."},
	{Name: "LOGICAL_OR", Description: "Gets the logical OR of all non-NULL expressions."},
	{Name: "LOWER", Description: "Formats alphabetic characters in a STRING value as lowercase. Formats ASCII characters in a BYTES value as lowercase."},
	{Name: "LPAD", Description: "Prepends a STRING or BYTES value with a pattern."},
	{Name: "LTRIM", Description: "Identical to the TRIM function, but only removes leading characters."},
	{Name: "MAKE_INTERVAL", Description: "Constructs an INTERVAL value."},
	{Name: "MAX", Description: "Gets the maximum non-NULL value."},
	{Name: "MAX_BY", Description: "Synonym for ANY_VALUE(x HAVING MAX y)."},
	{Name: "MD5", Description: "Computes the hash of a STRING or BYTES value, using the MD5 algorithm."},
	{Name: "MIN", Description: "Gets the minimum non-NULL value."},
	{Name: "MIN_BY", Description: "Synonym for ANY_VALUE(x HAVING MIN y)."},
	{Name: "MOD", Description: "Gets the remainder of the division of X by Y."},
	{Name: "NET.HOST", Description: "Gets the hostname from a URL."},
	{Name: "NET.IP_FROM_STRING", Description: "Converts an IPv4 or IPv6 address from a STRING value to a BYTES value in network byte order."},
	{Name: "NET.IP_NET_MASK", Description: "Gets a network mask."},
	{Name: "NET.IP_TO_STRING", Description: "Converts an IPv4 or IPv6 address from a BYTES value in network byte order to a STRING value."},
	{Name: "NET.IP_TRUNC", Description: "Converts a BYTES IPv4 or IPv6 address in network byte order to a BYTES subnet address."},
	{Name: "NET.IPV4_FROM_INT64", Description: "Converts an IPv4 address from an INT64 value to a BYTES value in network byte order."},
	{Name: "NET.IPV4_TO_INT64", Description: "Converts an IPv4 address from a BYTES value in network byte order to an INT64 value."},
	{Name: "NET.PUBLIC_SUFFIX", Description: "Gets the public suffix from a URL."},
	{Name: "NET.REG_DOMAIN", Description: "Gets the registered or registrable domain from a URL."},
	{Name: "NET.SAFE_IP_FROM_STRING", Description: "Similar to the NET.IP_FROM_STRING, but returns NULL instead of producing an error if the input is invalid."},
	{Name: "NODES", Description: "Gets the nodes in a graph path. The resulting array retains the original order in the graph path."},
	{Name: "NORMALIZE", Description: "Case-sensitively normalizes the characters in a STRING value."},
	{Name: "NORMALIZE_AND_CASEFOLD", Description: "Case-insensitively normalizes the characters in a STRING value."},
	{Name: "NTH_VALUE", Description: "Gets a value for the Nth row of the current window frame."},
	{Name: "NTILE", Description: "Gets the quantile bucket number (1-based) of each row within a window."},
	{Name: "OBJ.FETCH_METADATA", Description: "Fetches Cloud Storage metadata for a partially populated ObjectRef value."},
	{Name: "OBJ.GET_ACCESS_URL", Description: "Returns access URLs for a Cloud Storage object."},
	{Name: "OBJ.GET_READ_URL", Description: "Returns a read URL and status for a Cloud Storage object."},
	{Name: "OBJ.MAKE_REF", Description: "Creates an ObjectRef value that contains reference information for a Cloud Storage object."},
	{Name: "OCTET_LENGTH", Description: "Alias for BYTE_LENGTH."},
	{Name: "PARSE_BIGNUMERIC", Description: "Converts a STRING value to a BIGNUMERIC value."},
	{Name: "PARSE_DATE", Description: "Converts a STRING value to a DATE value."},
	{Name: "PARSE_DATETIME", Description: "Converts a STRING value to a DATETIME value."},
	{Name: "PARSE_JSON", Description: "Converts a JSON-formatted STRING value to a JSON value."},
	{Name: "PARSE_NUMERIC", Description: "Converts a STRING value to a NUMERIC value."},
	{Name: "PARSE_TIME", Description: "Converts a STRING value to a TIME value."},
	{Name: "PARSE_TIMESTAMP", Description: "Converts a STRING value to a TIMESTAMP value."},
	{Name: "PATH_FIRST", Description: "Gets the first node in a graph path."},
	{Name: "PATH_LAST", Description: "Gets the last node in a graph path."},
	{Name: "PATH_LENGTH", Description: "Gets the number of edges in a graph path."},
	{Name: "PERCENT_RANK", Description: "Gets the percentile rank (from 0 to 1) of each row within a window."},
	{Name: "PERCENTILE_CONT", Description: "Computes the specified percentile for a value, using linear interpolation. / DIFFERENTIAL_PRIVACY-supported PERCENTILE_CONT. Computes a differentially-private percentile across privacy unit columns in a query with a DIFFERENTIAL_PRIVACY clause."},
	{Name: "PERCENTILE_DISC", Description: "Computes the specified percentile for a discrete value."},
	{Name: "POW", Description: "Produces the value of X raised to the power of Y."},
	{Name: "POWER", Description: "Synonym of POW."},
	{Name: "RAND", Description: "Generates a pseudo-random value of type FLOAT64 in the range of [0, 1)."},
	{Name: "RANGE", Description: "Constructs a range of DATE, DATETIME, or TIMESTAMP values."},
	{Name: "RANGE_BUCKET", Description: "Scans through a sorted array and returns the 0-based position of a point's upper bound."},
	{Name: "RANGE_CONTAINS", Description: "Signature 1: Checks if one range is in another range. Signature 2: Checks if a value is in a range."},
	{Name: "RANGE_END", Description: "Gets the upper bound of a range."},
	{Name: "RANGE_INTERSECT", Description: "Gets a segment of two ranges that intersect."},
	{Name: "RANGE_OVERLAPS", Description: "Checks if two ranges overlap."},
	{Name: "RANGE_SESSIONIZE", Description: "Produces a table of sessionized ranges."},
	{Name: "RANGE_START", Description: "Gets the lower bound of a range."},
	{Name: "RANK", Description: "Gets the rank (1-based) of each row within a window."},
	{Name: "REGEXP_CONTAINS", Description: "Checks if a value is a partial match for a regular expression."},
	{Name: "REGEXP_EXTRACT", Description: "Produces a substring that matches a regular expression."},
	{Name: "REGEXP_EXTRACT_ALL", Description: "Produces an array of all substrings that match a regular expression."},
	{Name: "REGEXP_INSTR", Description: "Finds the position of a regular expression match in a value, optionally starting the search at a given offset or occurrence."},
	{Name: "REGEXP_REPLACE", Description: "Produces a STRING value where all substrings that match a regular expression are replaced with a specified value."},
	{Name: "REGEXP_SUBSTR", Description: "Synonym for REGEXP_EXTRACT."},
	{Name: "REPEAT", Description: "Produces a STRING or BYTES value that consists of an original value, repeated."},
	{Name: "REPLACE", Description: "Replaces all occurrences of a pattern with another pattern in a STRING or BYTES value."},
	{Name: "REVERSE", Description: "Reverses a STRING or BYTES value."},
	{Name: "RIGHT", Description: "Gets the specified rightmost portion from a STRING or BYTES value."},
	{Name: "ROUND", Description: "Rounds X to the nearest integer or rounds X to N decimal places after the decimal point."},
	{Name: "ROW_NUMBER", Description: "Gets the sequential row number (1-based) of each row within a window."},
	{Name: "RPAD", Description: "Appends a STRING or BYTES value with a pattern."},
	{Name: "RTRIM", Description: "Identical to the TRIM function, but only removes trailing characters."},
	{Name: "S2_CELLIDFROMPOINT", Description: "Gets the S2 cell ID covering a point GEOGRAPHY value."},
	{Name: "S2_COVERINGCELLIDS", Description: "Gets an array of S2 cell IDs that cover a GEOGRAPHY value."},
	{Name: "SAFE_ADD", Description: "Equivalent to the addition operator (X + Y), but returns NULL if overflow occurs."},
	{Name: "SAFE_CAST", Description: "Similar to the CAST function, but returns NULL when a runtime error is produced."},
	{Name: "SAFE_CONVERT_BYTES_TO_STRING", Description: "Converts a BYTES value to a STRING value and replace any invalid UTF-8 characters with the Unicode replacement character, U+FFFD."},
	{Name: "SAFE_DIVIDE", Description: "Equivalent to the division operator (X / Y), but returns NULL if an error occurs."},
	{Name: "SAFE_MULTIPLY", Description: "Equivalent to the multiplication operator (X * Y), but returns NULL if overflow occurs."},
	{Name: "SAFE_NEGATE", Description: "Equivalent to the unary minus operator (-X), but returns NULL if overflow occurs."},
	{Name: "SAFE_SUBTRACT", Description: "Equivalent to the subtraction operator (X - Y), but returns NULL if overflow occurs."},
	{Name: "SEARCH", Description: "Checks to see whether a table or other search data contains a set of search terms."},
	{Name: "SEC", Description: "Computes the secant of X."},
	{Name: "SECH", Description: "Computes the hyperbolic secant of X."},
	{Name: "SESSION_USER", Description: "Get the email address or principal identifier of the user that's running the query."},
	{Name: "SHA1", Description: "Computes the hash of a STRING or BYTES value, using the SHA-1 algorithm."},
	{Name: "SHA256", Description: "Computes the hash of a STRING or BYTES value, using the SHA-256 algorithm."},
	{Name: "SHA512", Description: "Computes the hash of a STRING or BYTES value, using the SHA-512 algorithm."},
	{Name: "SIGN", Description: "Produces -1 , 0, or +1 for negative, zero, and positive arguments respectively."},
	{Name: "SIN", Description: "Computes the sine of X."},
	{Name: "SINH", Description: "Computes the hyperbolic sine of X."},
	{Name: "SOURCE_NODE_ID", Description: "Gets a unique identifier of a graph edge's source node."},
	{Name: "SOUNDEX", Description: "Gets the Soundex codes for words in a STRING value."},
	{Name: "SPLIT", Description: "Splits a STRING or BYTES value, using a delimiter."},
	{Name: "SQRT", Description: "Computes the square root of X."},
	{Name: "ST_ANGLE", Description: "Takes three point GEOGRAPHY values, which represent two intersecting lines, and returns the angle between these lines."},
	{Name: "ST_AREA", Description: "Gets the area covered by the polygons in a GEOGRAPHY value."},
	{Name: "ST_ASBINARY", Description: "Converts a GEOGRAPHY value to a BYTES WKB geography value."},
	{Name: "ST_ASGEOJSON", Description: "Converts a GEOGRAPHY value to a STRING GeoJSON geography value."},
	{Name: "ST_ASTEXT", Description: "Converts a GEOGRAPHY value to a STRING WKT geography value."},
	{Name: "ST_AZIMUTH", Description: "Gets the azimuth of a line segment formed by two point GEOGRAPHY values."},
	{Name: "ST_BOUNDARY", Description: "Gets the union of component boundaries in a GEOGRAPHY value."},
	{Name: "ST_BOUNDINGBOX", Description: "Gets the bounding box for a GEOGRAPHY value."},
	{Name: "ST_BUFFER", Description: "Gets the buffer around a GEOGRAPHY value, using a specific number of segments."},
	{Name: "ST_BUFFERWITHTOLERANCE", Description: "Gets the buffer around a GEOGRAPHY value, using tolerance."},
	{Name: "ST_CENTROID", Description: "Gets the centroid of a GEOGRAPHY value."},
	{Name: "ST_CENTROID_AGG", Description: "Gets the centroid of a set of GEOGRAPHY values."},
	{Name: "ST_CLOSESTPOINT", Description: "Gets the point on a GEOGRAPHY value which is closest to any point in a second GEOGRAPHY value."},
	{Name: "ST_CLUSTERDBSCAN", Description: "Performs DBSCAN clustering on a group of GEOGRAPHY values and produces a 0-based cluster number for this row."},
	{Name: "ST_CONTAINS", Description: "Checks if one GEOGRAPHY value contains another GEOGRAPHY value."},
	{Name: "ST_CONVEXHULL", Description: "Returns the convex hull for a GEOGRAPHY value."},
	{Name: "ST_COVEREDBY", Description: "Checks if all points of a GEOGRAPHY value are on the boundary or interior of another GEOGRAPHY value."},
	{Name: "ST_COVERS", Description: "Checks if all points of a GEOGRAPHY value are on the boundary or interior of another GEOGRAPHY value."},
	{Name: "ST_DIFFERENCE", Description: "Gets the point set difference between two GEOGRAPHY values."},
	{Name: "ST_DIMENSION", Description: "Gets the dimension of the highest-dimensional element in a GEOGRAPHY value."},
	{Name: "ST_DISJOINT", Description: "Checks if two GEOGRAPHY values are disjoint (don't intersect)."},
	{Name: "ST_DISTANCE", Description: "Gets the shortest distance in meters between two GEOGRAPHY values."},
	{Name: "ST_DUMP", Description: "Returns an array of simple GEOGRAPHY components in a GEOGRAPHY value."},
	{Name: "ST_DWITHIN", Description: "Checks if any points in two GEOGRAPHY values are within a given distance."},
	{Name: "ST_ENDPOINT", Description: "Gets the last point of a linestring GEOGRAPHY value."},
	{Name: "ST_EQUALS", Description: "Checks if two GEOGRAPHY values represent the same GEOGRAPHY value."},
	{Name: "ST_EXTENT", Description: "Gets the bounding box for a group of GEOGRAPHY values."},
	{Name: "ST_EXTERIORRING", Description: "Returns a linestring GEOGRAPHY value that corresponds to the outermost ring of a polygon GEOGRAPHY value."},
	{Name: "ST_GEOGFROM", Description: "Converts a STRING or BYTES value into a GEOGRAPHY value."},
	{Name: "ST_GEOGFROMGEOJSON", Description: "Converts a STRING GeoJSON geometry value into a GEOGRAPHY value."},
	{Name: "ST_GEOGFROMTEXT", Description: "Converts a STRING WKT geometry value into a GEOGRAPHY value."},
	{Name: "ST_GEOGFROMWKB", Description: "Converts a BYTES or hexadecimal-text STRING WKT geometry value into a GEOGRAPHY value."},
	{Name: "ST_GEOGPOINT", Description: "Creates a point GEOGRAPHY value for a given longitude and latitude."},
	{Name: "ST_GEOGPOINTFROMGEOHASH", Description: "Gets a point GEOGRAPHY value that's in the middle of a bounding box defined in a STRING GeoHash value."},
	{Name: "ST_GEOHASH", Description: "Converts a point GEOGRAPHY value to a STRING GeoHash value."},
	{Name: "ST_GEOMETRYTYPE", Description: "Gets the Open Geospatial Consortium (OGC) geometry type for a GEOGRAPHY value."},
	{Name: "ST_HAUSDORFFDISTANCE", Description: "Gets the discrete Hausdorff distance between two geometries."},
	{Name: "ST_HAUSDORFFDWITHIN", Description: "Checks if the Hausdorff distance between two GEOGRAPHY values is within a given distance."},
	{Name: "ST_INTERIORRINGS", Description: "Gets the interior rings of a polygon GEOGRAPHY value."},
	{Name: "ST_INTERSECTION", Description: "Gets the point set intersection of two GEOGRAPHY values."},
	{Name: "ST_INTERSECTS", Description: "Checks if at least one point appears in two GEOGRAPHY values."},
	{Name: "ST_INTERSECTSBOX", Description: "Checks if a GEOGRAPHY value intersects a rectangle."},
	{Name: "ST_ISCLOSED", Description: "Checks if all components in a GEOGRAPHY value are closed."},
	{Name: "ST_ISCOLLECTION", Description: "Checks if the total number of points, linestrings, and polygons is greater than one in a GEOGRAPHY value."},
	{Name: "ST_ISEMPTY", Description: "Checks if a GEOGRAPHY value is empty."},
	{Name: "ST_ISRING", Description: "Checks if a GEOGRAPHY value is a closed, simple linestring."},
	{Name: "ST_LENGTH", Description: "Gets the total length of lines in a GEOGRAPHY value."},
	{Name: "ST_LINEINTERPOLATEPOINT", Description: "Gets a point at a specific fraction in a linestring GEOGRAPHY value."},
	{Name: "ST_LINELOCATEPOINT", Description: "Gets a section of a linestring GEOGRAPHY value between the start point and a point GEOGRAPHY value."},
	{Name: "ST_LINESUBSTRING", Description: "Gets a segment of a single linestring at a specific starting and ending fraction."},
	{Name: "ST_MAKELINE", Description: "Creates a linestring GEOGRAPHY value by concatenating the point and linestring vertices of GEOGRAPHY values."},
	{Name: "ST_MAKEPOLYGON", Description: "Constructs a polygon GEOGRAPHY value by combining a polygon shell with polygon holes."},
	{Name: "ST_MAKEPOLYGONORIENTED", Description: "Constructs a polygon GEOGRAPHY value, using an array of linestring GEOGRAPHY values. The vertex ordering of each linestring determines the orientation of each polygon ring."},
	{Name: "ST_MAXDISTANCE", Description: "Gets the longest distance between two non-empty GEOGRAPHY values."},
	{Name: "ST_NPOINTS", Description: "An alias of ST_NUMPOINTS."},
	{Name: "ST_NUMGEOMETRIES", Description: "Gets the number of geometries in a GEOGRAPHY value."},
	{Name: "ST_NUMPOINTS", Description: "Gets the number of vertices in the a GEOGRAPHY value."},
	{Name: "ST_PERIMETER", Description: "Gets the length of the boundary of the polygons in a GEOGRAPHY value."},
	{Name: "ST_POINTN", Description: "Gets the point at a specific index of a linestring GEOGRAPHY value."},
	{Name: "ST_REGIONSTATS", Description: "Computes statistics describing the pixels in a geospatial raster image that intersect a GEOGRAPHY value."},
	{Name: "ST_SIMPLIFY", Description: "Converts a GEOGRAPHY value into a simplified GEOGRAPHY value, using tolerance."},
	{Name: "ST_SNAPTOGRID", Description: "Produces a GEOGRAPHY value, where each vertex has been snapped to a longitude/latitude grid."},
	{Name: "ST_STARTPOINT", Description: "Gets the first point of a linestring GEOGRAPHY value."},
	{Name: "ST_TOUCHES", Description: "Checks if two GEOGRAPHY values intersect and their interiors have no elements in common."},
	{Name: "ST_UNION", Description: "Gets the point set union of multiple GEOGRAPHY values."},
	{Name: "ST_UNION_AGG", Description: "Aggregates over GEOGRAPHY values and gets their point set union."},
	{Name: "ST_WITHIN", Description: "Checks if one GEOGRAPHY value contains another GEOGRAPHY value."},
	{Name: "ST_X", Description: "Gets the longitude from a point GEOGRAPHY value."},
	{Name: "ST_Y", Description: "Gets the latitude from a point GEOGRAPHY value."},
	{Name: "STARTS_WITH", Description: "Checks if a STRING or BYTES value is a prefix of another value."},
	{Name: "STDDEV", Description: "An alias of the STDDEV_SAMP function."},
	{Name: "STDDEV_POP", Description: "Computes the population (biased) standard deviation of the values."},
	{Name: "STDDEV_SAMP", Description: "Computes the sample (unbiased) standard deviation of the values."},
	{Name: "STRING", Description: "Converts a JSON string to a SQL STRING value. / Converts a TIMESTAMP value to a STRING value."},
	{Name: "STRING_AGG", Description: "Concatenates non-NULL STRING or BYTES values."},
	{Name: "STRPOS", Description: "Finds the position of the first occurrence of a subvalue inside another value."},
	{Name: "SUBSTR", Description: "Gets a portion of a STRING or BYTES value."},
	{Name: "SUBSTRING", Description: "Alias for SUBSTR"},
	{Name: "SUM", Description: "Gets the sum of non-NULL values. / DIFFERENTIAL_PRIVACY-supported SUM. Gets the differentially-private sum of non-NULL, non-NaN values in a query with a DIFFERENTIAL_PRIVACY clause."},
	{Name: "TAN", Description: "Computes the tangent of X."},
	{Name: "TANH", Description: "Computes the hyperbolic tangent of X."},
	{Name: "TEXT_ANALYZE", Description: "Extracts terms (tokens) from text and converts them into a tokenized document."},
	{Name: "TF_IDF", Description: "Evaluates how relevant a term (token) is to a tokenized document in a set of tokenized documents."},
	{Name: "TIME", Description: "Constructs a TIME value."},
	{Name: "TIME_ADD", Description: "Adds a specified time interval to a TIME value."},
	{Name: "TIME_DIFF", Description: "Gets the number of unit boundaries between two TIME values at a particular time granularity."},
	{Name: "TIME_SUB", Description: "Subtracts a specified time interval from a TIME value."},
	{Name: "TIME_TRUNC", Description: "Truncates a TIME value at a particular granularity."},
	{Name: "TIMESTAMP", Description: "Constructs a TIMESTAMP value."},
	{Name: "TIMESTAMP_ADD", Description: "Adds a specified time interval to a TIMESTAMP value."},
	{Name: "TIMESTAMP_BUCKET", Description: "Gets the lower bound of the timestamp bucket that contains a timestamp."},
	{Name: "TIMESTAMP_DIFF", Description: "Gets the number of unit boundaries between two TIMESTAMP values at a particular time granularity."},
	{Name: "TIMESTAMP_MICROS", Description: "Converts the number of microseconds since 1970-01-01 00:00:00 UTC to a TIMESTAMP."},
	{Name: "TIMESTAMP_MILLIS", Description: "Converts the number of milliseconds since 1970-01-01 00:00:00 UTC to a TIMESTAMP."},
	{Name: "TIMESTAMP_SECONDS", Description: "Converts the number of seconds since 1970-01-01 00:00:00 UTC to a TIMESTAMP."},
	{Name: "TIMESTAMP_SUB", Description: "Subtracts a specified time interval from a TIMESTAMP value."},
	{Name: "TIMESTAMP_TRUNC", Description: "Truncates a TIMESTAMP or DATETIME value at a particular granularity."},
	{Name: "TO_BASE32", Description: "Converts a BYTES value to a base32-encoded STRING value."},
	{Name: "TO_BASE64", Description: "Converts a BYTES value to a base64-encoded STRING value."},
	{Name: "TO_CODE_POINTS", Description: "Converts a STRING or BYTES value into an array of extended ASCII code points."},
	{Name: "TO_HEX", Description: "Converts a BYTES value to a hexadecimal STRING value."},
	{Name: "TO_JSON", Description: "Converts a SQL value to a JSON value."},
	{Name: "TO_JSON_STRING", Description: "Converts a SQL value to a JSON-formatted STRING value."},
	{Name: "TRANSLATE", Description: "Within a value, replaces each source character with the corresponding target character."},
	{Name: "TRIM", Description: "Removes the specified leading and trailing Unicode code points or bytes from a STRING or BYTES value."},
	{Name: "TRUNC", Description: "Rounds a number like ROUND(X) or ROUND(X, N), but always rounds towards zero and never overflows."},
	{Name: "TYPEOF", Description: "Gets the name of the data type for an expression."},
	{Name: "UNICODE", Description: "Gets the Unicode code point for the first character in a value."},
	{Name: "UNIX_DATE", Description: "Converts a DATE value to the number of days since 1970-01-01."},
	{Name: "UNIX_MICROS", Description: "Converts a TIMESTAMP value to the number of microseconds since 1970-01-01 00:00:00 UTC."},
	{Name: "UNIX_MILLIS", Description: "Converts a TIMESTAMP value to the number of milliseconds since 1970-01-01 00:00:00 UTC."},
	{Name: "UNIX_SECONDS", Description: "Converts a TIMESTAMP value to the number of seconds since 1970-01-01 00:00:00 UTC."},
	{Name: "UPPER", Description: "Formats alphabetic characters in a STRING value as uppercase. Formats ASCII characters in a BYTES value as uppercase."},
	{Name: "VAR_POP", Description: "Computes the population (biased) variance of the values."},
	{Name: "VAR_SAMP", Description: "Computes the sample (unbiased) variance of the values."},
	{Name: "VARIANCE", Description: "An alias of VAR_SAMP."},
	{Name: "VECTOR_SEARCH", Description: "Performs a semantic search or a hybrid search on embeddings to find similar entities."},
	{Name: "VECTOR_INDEX.STATISTICS", Description: "Calculate how much an indexed table's data has drifted between when a vector index was trained and the present."},
}
